# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-02 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_actionsummary_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='deleted',
        ),
        migrations.AddField(
            model_name='like',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
    ]
