# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-20 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20180807_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover_image',
            field=models.CharField(default='http://static.dogrod.com/media/i-am-root.png', max_length=120),
        ),
    ]
