# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-22 08:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_post_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='deleted',
        ),
        migrations.AddField(
            model_name='comment',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_comment', to='blog.Comment'),
        ),
    ]
