# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-26 06:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20180822_1659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-create_at',)},
        ),
    ]
