# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='image')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
